name: Manual Deployment with Terraform and Ansible

on:
  workflow_dispatch: # Allows for manual triggering in the GitHub UI

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest
    outputs:
      instance_ip: ${{ steps.output.outputs.instance_ip }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Changes
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve

    - name: Fetch Instance IP
      id: output
      run: echo "::set-output name=instance_ip::$(terraform output instance_ip)"

  ansible:
    name: Configure with Ansible
    needs: terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      env:
        INSTANCE_IP: ${{ needs.terraform.outputs.instance_ip }}
      run: ansible-playbook -i $INSTANCE_IP, playbook.yml